/**
 * WhatsApp bot: English & Swahili translations.
 * Use T(session, key) to get string for session.lang ('en' | 'sw').
 */

const L = {
  en: {
    // Home
    home_welcome: 'Welcome to',
    home_choose: 'Choose service:',
    home_type_zero: 'Type 0 anytime to go back here.',
    home_main_services: 'MAIN SERVICES',
    // Menu items
    menu_view: 'View Our Menu',
    menu_view_desc: 'View menu and order',
    rate_service: 'Rate Service',
    rate_desc: 'Give feedback',
    pay_bill: 'Pay Bill',
    pay_bill_desc: 'Pay your bill',
    tip: 'Tip',
    tip_desc: 'Tip the waiter',
    call_waiter: 'Call Waiter',
    call_waiter_desc: 'Request assistance',
    customer_support: 'Customer Support',
    customer_support_desc: 'Contact support',
    change_language: 'Change language',
    change_language_desc: 'Swahili / English',
    exit: 'Exit',
    exit_desc: 'Leave',
    // Language selection
    select_language: 'Select language:',
    lang_english: 'English',
    lang_swahili: 'Kiswahili',
    language_changed: 'Language set to English.',
    language_changed_sw: 'Lugha imewekwa kwa Kiswahili.',
    // Menu PDF
    downloading_menu: 'Downloading our menu...',
    here_is_menu: 'Here is our menu!',
    menu_type_order: 'Type your order (e.g. Chips 2, Soda 1) or type 0 to go back.',
    menu_commands: 'Commands:',
    menu_cmd_zero: '0 = Back to main menu',
    menu_cmd_order: 'Order = Type item name and quantity (e.g. Chips 2, Soda 1)',
    menu_cmd_confirm: 'CONFIRM / KAMILISHA / THIBITISHA / SEND = Submit full order after you pick table.',
    menu_prompt_after_table: 'See menu PDF above. Type more dishes, then CONFIRM or KAMILISHA when done. 0 = home.',
    menu_confirm_keywords_hint: 'Keywords: CONFIRM, KAMILISHA, THIBITISHA, SEND, NITUME',
    menu_item_added_ok: 'Added:',
    menu_item_added_footer: 'Keep adding dishes, then CONFIRM to send the full order.',
    menu_confirm_empty_error: 'Nothing to send yet — add items first e.g. Chips 2, then CONFIRM.',
    home_btn: 'Home (0)',
    menu_not_available: 'Sorry, our menu PDF is not available. Type 0 to go back.',
    // Pay bill / phone
    enter_phone_billed: 'Enter phone number to be billed',
    enter_phone_tip: 'Enter phone number to tip (e.g., 0712345678):',
    enter_phone_pay: 'Enter phone number to pay (e.g., 0712345678):',
    enter_amount: 'Enter amount to pay (Tsh):',
    tip_amount: 'Tip',
    invalid_number: 'Invalid number. Try again.',
    invalid_amount: 'Invalid amount. Enter numbers only.',
    sending_request: 'Sending payment request...',
    request_sent: 'Request sent to',
    confirm_on_phone: 'Please confirm on your phone.',
    bot_confirm_auto: 'TipTap will confirm automatically once payment is received.',
    // Customer support
    support_title: 'Customer Support',
    support_call: 'Call or WhatsApp:',
    support_type_zero: 'Type 0 to go back to main menu.',
    back_to_menu: 'Back to Menu',
    choose: 'Choose:',
    // General
    table: 'Table',
    goodbye: 'Goodbye! Thank you for visiting us.',
    session_expired: 'Your *{name}* session has expired due to inactivity.\n\nThank you for visiting us!',
    session_expired_no_name: 'Your session has expired due to inactivity.\n\nThank you for visiting us!',
    processing_order: 'Processing your order...',
    order_received: 'Order Received!',
    order_id: 'Order #',
    items_found: 'Items found:',
    total: 'Total:',
    waiter_confirm: 'Waiter is coming to confirm...',
    pay_now: 'Pay Now',
    track_status: 'Track Status',
    home: 'Home',
    error_try_again: 'Technical error. Please try again.',
    error_order: 'We could not understand your order.',
    try_clear: 'Please try to type clearly (e.g., "Chips 2, Soda 1"). Type 0 to go back.',
    verifying: 'Verifying...',
    invalid_qr: 'Invalid QR Code or Tag.',
    enter_table: 'Enter table number (e.g., 7):',
    valid_table: 'Please enter a valid table number.',
    order_which_table: 'Which table are you at?',
    order_reply_table_number: 'Reply with the table number (e.g. 1, 2, 3).',
    thanks_feedback: 'Thanks for your feedback!',
    thanks_using_tiptap: 'Thanks for using TipTap!\n\nWelcome again! 👋',
    comment_prompt: 'Enter comment or type END to finish',
    not_understood: "Sorry, I didn't understand. Type \"Hi\" to start over.",
    // Call waiter – offline & flow
    waiter_offline_msg: '*{name}* is currently *offline*.\n\nYou can:\n• Type *0* – Go back to menu\n• Type *EXIT* – Leave completely\n• *Scan another waiter\'s QR* – To get a waiter who is online',
    call_waiter_sent: 'Request for *{label}* sent! Waiter is coming shortly.',
    call_waiter_failed: 'Sorry, failed to send request. Please try again later.',
    call_waiter_table_invalid: 'Please enter a valid table number (e.g. 1, 2, 5) or choose from the list.',
    waiters_list_title: 'Our Waiters',
    waiters_list_subtitle: 'Choose a waiter to call (only online waiters can receive calls).',
    waiters_list_empty: 'Sorry, no waiters available right now.',
    waiters_list_btn: 'View Waiters',
    waiters_offline_badge: '(Offline)',
    waiters_tap_to_call: 'Tap to call',
    waiters_not_on_duty: 'Not on duty',
    feedback_prompt: '⭐ *Feedback*\nWhat would you like to rate?',
    feedback_rate_restaurant: '🏢 Restaurant Service',
    feedback_rate_waiter_btn: '🙋 Waiter Service',
    feedback_waiter_pick_title: '🙋 Choose a waiter to rate:',
    feedback_waiter_pick_section: 'Waiters',
    feedback_waiter_tap_rate: 'Tap to rate',
    feedback_rating_for: '⭐ *Rating for {name}*',
    feedback_rating_generic: '⭐ *Rating*',
    feedback_give_stars: 'Give us your feedback:',
    tip_waiter_pick_title: '💝 Choose a waiter to tip:',
    tip_waiter_pick_section: 'Waiters',
    tip_waiter_tap_tip: 'Give tip',
  tap_powered_by: 'Powered by TipTap',
  tap_welcome_help: 'How can I help you today?',
  tap_welcome_sub: 'Tap an option below',
  tap_waiter_label: 'Your waiter',
  tap_services_all: 'ALL SERVICES',
  tap_services_pick: 'Pick what you need:',
  tap_open_services: 'Open Services',
  tap_section_food: 'Food & Drinks',
  tap_section_pay: 'Payments',
  tap_section_feedback: 'Feedback',
  tap_section_settings: 'Settings',
  tap_pay_methods: 'M-Pesa, Airtel, cash, card',
  tap_tip_waiter: 'Thank {name}',
  tap_rate_waiter: 'Rate {name}',
  tap_rate_service: 'Rate Service',
  tap_exit: 'Leave chat',
  start_welcome_title: 'Welcome to',
  start_welcome: 'Scan a waiter QR code or type a restaurant name to begin.',
  call_waiter_short: 'Call Waiter',
  call_waiter_arriving: '{name} has been notified!',
  call_waiter_eta: 'On the way · about 2 min',
  },
  sw: {
    home_welcome: 'Karibu',
    home_choose: 'Chagua huduma:',
    home_type_zero: 'Andika 0 wakati wowote kurudi hapa.',
    home_main_services: 'HUDUMA ZA KUANZIA',
    menu_view: 'Tazama Menu',
    menu_view_desc: 'Tazama menu na kuagiza',
    rate_service: 'Kadiria Huduma',
    rate_desc: 'Toa maoni',
    pay_bill: 'Lipa Bili',
    pay_bill_desc: 'Lipa bili yako',
    tip: 'Mchango',
    tip_desc: 'Mpa mchango mhudumu',
    call_waiter: 'Mwalika Mhudumu',
    call_waiter_desc: 'Omba msaada',
    customer_support: 'Msaada wa Wateja',
    customer_support_desc: 'Wasiliana na msaada',
    change_language: 'Badilisha lugha',
    change_language_desc: 'Kiswahili / English',
    exit: 'Ondoka',
    exit_desc: 'Toka',
    select_language: 'Chagua lugha:',
    lang_english: 'English',
    lang_swahili: 'Kiswahili',
    language_changed: 'Language set to English.',
    language_changed_sw: 'Lugha imewekwa kwa Kiswahili.',
    downloading_menu: 'Inapakua menu yetu (PDF)...',
    here_is_menu: 'Hii ni menu yetu!',
    menu_type_order: 'Andika maagizo (mf. Chips 2, Soda 1) au andika 0 kurudi.',
    menu_commands: 'Maagizo:',
    menu_cmd_zero: '0 = Rudi kwenye menu kuu',
    menu_cmd_order: 'Agizo = Andika jina la kitu na idadi (mf. Chips 2, Soda 1)',
    menu_cmd_confirm: 'CONFIRM / KAMILISHA / THIBITISHA / SEND = Tumia maagizo yote baada ya kuchagua meza.',
    menu_prompt_after_table: '👆 Menu PDF iko juu.\n\n✏️ Endelea kuandika vyakula (idadi + jina).\n🔔 Andika CONFIRM (au KAMILISHA) umalize.\n0 = ghairi irudi home.',
    menu_confirm_keywords_hint: 'Tumia: CONFIRM · KAMILISHA · THIBITISHA · SEND · NITUME',
    menu_item_added_ok: 'Imeongezwa:',
    menu_item_added_footer: '_Endelea kuongeza, kisha CONFIRM kutuma kwenye jikoni._',
    menu_confirm_empty_error: 'Bado hakuna kitu — andika kwanza (mf. Chips 2), kisha CONFIRM.',
    home_btn: 'Nyumbani (0)',
    menu_not_available: 'Samahani, menu PDF haipatikani. Andika 0 kurudi.',
    enter_phone_billed: 'Ingiza nambari ya simu ya kulipiwa',
    enter_phone_tip: 'Ingiza nambari ya simu ya mchango (mf. 0712345678):',
    enter_phone_pay: 'Ingiza nambari ya simu ya kulipa (mf. 0712345678):',
    enter_amount: 'Ingiza kiasi cha kulipa (Tsh):',
    tip_amount: 'Mchango',
    invalid_number: 'Nambari si sahihi. Jaribu tena.',
    invalid_amount: 'Kiasi si sahihi. Ingiza nambari tu.',
    sending_request: 'Inatumia ombi la malipo...',
    request_sent: 'Ombi limetumwa kwa',
    confirm_on_phone: 'Tafadhali thibitisha kwenye simu yako.',
    bot_confirm_auto: 'TipTap itathibitisha moja kwa moja malipo yanapopokelewa.',
    support_title: 'Msaada wa Wateja',
    support_call: 'Piga au WhatsApp:',
    support_type_zero: 'Andika 0 kurudi kwenye menu kuu.',
    back_to_menu: 'Rudi kwenye Menu',
    choose: 'Chagua:',
    table: 'Meza',
    goodbye: 'Kwaheri! Asante kwa kutembelea.',
    session_expired: 'Kipindi chako cha *{name}* kimeisha kwa kutokuwa na shughuli.\n\nAsante kwa kutembelea!',
    session_expired_no_name: 'Kipindi chako kimeisha kwa kutokuwa na shughuli.\n\nAsante kwa kutembelea!',
    processing_order: 'Inachakata maagizo yako...',
    order_received: 'Agizo Limepokelewa!',
    order_id: 'Agizo #',
    items_found: 'Vitu vilivyopatikana:',
    total: 'Jumla:',
    waiter_confirm: 'Mhudumu anakuja kuthibitisha...',
    pay_now: 'Lipa Sasa',
    track_status: 'Ufuatiliaji',
    home: 'Nyumbani',
    error_try_again: 'Hitilafu ya kiufundi. Tafadhali jaribu tena.',
    error_order: 'Hatukuweza kuelewa agizo lako.',
    try_clear: 'Tafadhali andika wazi (mf. "Chips 2, Soda 1"). Andika 0 kurudi.',
    verifying: 'Inathibitisha...',
    invalid_qr: 'Msimbo wa QR au Tag si sahihi.',
    enter_table: 'Ingiza nambari ya meza (mf. 7):',
    valid_table: 'Tafadhali ingiza nambari sahihi ya meza.',
    order_which_table: 'Upo meza namba ngapi?',
    order_reply_table_number: 'Jibu kwa nambari ya meza (mf. 1, 2, 3).',
    thanks_feedback: 'Asante kwa maoni yako!',
    thanks_using_tiptap: 'Asante kwa kutumia TipTap!\n\nKaribu tena! 👋',
    comment_prompt: 'Ingiza maoni au andika END kumaliza',
    not_understood: 'Samahani, sikuweza kuelewa. Andika "Hi" kuanza.',
    // Call waiter – offline & flow
    waiter_offline_msg: '*{name}* sasa *haiko online*.\n\nUnaweza:\n• Andika *0* – Rudi kwenye menu\n• Andika *EXIT* – Ondoka kabisa\n• *Scan QR ya waiter mwingine* – Ili kupata mhudumu aliye online',
    call_waiter_sent: 'Ombi la *{label}* limepokelewa! Mhudumu anakuja hivi karibuni.',
    call_waiter_failed: 'Samahani, kutumia ombi kumeshindwa. Tafadhali jaribu tena baadaye.',
    call_waiter_table_invalid: 'Tafadhali ingiza nambari sahihi ya meza (mf. 1, 2, 5) au chagua kutoka orodha.',
    waiters_list_title: 'Wahudumu Wetu',
    waiters_list_subtitle: 'Chagua mhudumu kumwita (wanaoona tu wanaweza kupokea wito).',
    waiters_list_empty: 'Samahani, hakuna wahudumu waliopo sasa.',
    waiters_list_btn: 'Tazama Wahudumu',
    waiters_offline_badge: '(Haiko kazini)',
    waiters_tap_to_call: 'Bonyeza kumuita',
    waiters_not_on_duty: 'Haiko kazini',
    feedback_prompt: '⭐ *Maoni*\nUngependa kupima nini?',
    feedback_rate_restaurant: '🏢 Huduma ya Restaurant',
    feedback_rate_waiter_btn: '🙋 Huduma ya Mhudumu',
    feedback_waiter_pick_title: '🙋 Chagua mhudumu wa kumfanyia rating:',
    feedback_waiter_pick_section: 'Wahudumu',
    feedback_waiter_tap_rate: 'Bonyeza kumfanyia rating',
    feedback_rating_for: '⭐ *Alama kwa {name}*',
    feedback_rating_generic: '⭐ *Alama*',
    feedback_give_stars: 'Toa maoni yako:',
    tip_waiter_pick_title: '💝 Chagua mhudumu wa kumpa tip:',
    tip_waiter_pick_section: 'Wahudumu',
    tip_waiter_tap_tip: 'Mpe tip',
  tap_powered_by: 'Powered by TipTap',
  tap_welcome_help: 'Ninaweza kukusaidia nini leo?',
  tap_welcome_sub: 'Bonyeza chaguo lako hapo chini',
  tap_waiter_label: 'Mhudumu wako',
  tap_services_all: 'HUDUMA ZOTE',
  tap_services_pick: 'Chagua unayoihitaji:',
  tap_open_services: 'Fungua Orodha',
  tap_section_food: 'Chakula',
  tap_section_pay: 'Malipo',
  tap_section_feedback: 'Maoni',
  tap_section_settings: 'Mipangilio',
  tap_pay_methods: 'M-Pesa, Airtel, taslimu, kadi',
  tap_tip_waiter: 'Mshukuru {name}',
  tap_rate_waiter: 'Mpe {name} alama',
  tap_rate_service: 'Pima Huduma',
  tap_exit: 'Maliza',
  start_welcome_title: 'Karibu',
  start_welcome: 'Scan QR ya mhudumu au andika jina la restaurant kuanza.',
  call_waiter_short: 'Mwambie Mhudumu',
  call_waiter_arriving: '{name} amejulishwa!',
  call_waiter_eta: 'Anakuja · karibu dakika 2',
  },
};

function T(session, key) {
  const lang = session.lang || 'en';
  const s = L[lang] && L[lang][key];
  return s !== undefined ? s : (L.en[key] || key);
}

module.exports = { L, T };
